channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - bzip2
  - ca-certificates
  - expat
  - libffi
  - libuuid
  - ncurses
  - openssl
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - pip:
      - aiohappyeyeballs==2.3.4
      - aiohttp==3.10.1
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.4.0
      - astunparse==1.6.3
      - attrs==24.1.0
      - autopep8==2.3.1
      - certifi==2024.7.4
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - cryptography==43.0.0
      - diskcache==5.6.3
      - distro==1.9.0
      - dm-tree==0.1.8
      - docker==7.1.0
      - docopt==0.6.2
      - docutils==0.21.2
      - duckdb==1.0.0
      - easyocr==1.7.1
      - filelock==3.13.1
      - flaml==2.1.2
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - gast==0.6.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.24.5
      - idna==3.7
      - imageio==2.34.2
      - importlib-metadata==8.2.0
      - jaraco-classes==3.4.0
      - jaraco-context==5.3.0
      - jaraco-functools==4.0.2
      - jeepney==0.8.0
      - jinja2==3.1.3
      - joblib==1.4.2
      - keyring==25.3.0
      - lazy-loader==0.4
      - lightning==2.3.3
      - lightning-utilities==0.11.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - more-itertools==10.3.0
      - mpmath==1.3.0
      - multidict==6.0.5
      - networkx==3.2.1
      - nh3==0.2.18
      - ninja==1.11.1.1
      - numpy==1.26.3
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-dali-cuda110
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - openai==1.39.0
      - opencv-python-headless==4.10.0.84
      - packaging==24.1
      - pandas==2.2.2
      - pillow
      - pkginfo==1.10.0
      - pyautogen==0.2.33
      - pyclipper==1.3.0.post5
      - pycodestyle==2.12.1
      - pycparser==2.22
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pygments==2.18.0
      - pyparsing==3.1.2
      - python-bidi==0.6.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytorch-lightning==2.3.3
      - pytz==2024.1
      - pyyaml==6.0.1
      - readme-renderer==44.0
      - regex==2024.7.24
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rfc3986==2.0.0
      - rich==13.7.1
      - safetensors==0.4.4
      - scikit-image==0.24.0
      - scikit-learn==1.5.1
      - scipy
      - secretstorage==3.3.3
      - sentence-transformers==3.0.1
      - shapely==2.0.5
      - six==1.16.0
      - sniffio==1.3.1
      - sympy==1.12
      - tenacity==9.0.0
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tifffile==2024.7.24
      - tiktoken==0.7.0
      - tokenizers==0.19.1
      - torchmetrics==1.4.1
      - tqdm==4.66.5
      - transformers==4.43.4
      - triton==3.0.0
      - twine==5.1.1
      - typing-extensions==4.9.0
      - tzdata==2024.1
      - urllib3==2.2.2
      - yarl==1.9.4
      - zipp==3.19.2
