db_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/duckdb_dir
data_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/data
output_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/outputs
prompt_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/prompts
log_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/logs
model_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/data/models
interactive_labeling_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/interactive_labeling_dir
llava_path: /gscratch/balazinska/enhaoz/VOCAL-UDF/data/models/llava-1.5-7b-hf # Not used
query_parser:
  temperature: 0.2
  top_p: 0.5
udf_proposer:
  temperature: 0.2
  top_p: 0.5
udf_generator:
  temperature: 0.2
  top_p: 0.5
clevrer:
  height: 320
  width: 480
  dataset_size: 10000
  n_train_selection: 10000
  n_test_selection: 10000
  n_test_distill: 1000
  features_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/duckdb_dir/features/clevrer_three_clips
  video_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/data/clevrer/
  video_frames_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/data/clevrer/video_frames
  onames:
    - object
cityflow:
  dataset_size: 1648
  n_train_selection: 5000
  n_test_selection: 5000
  n_test_distill: 1000
  features_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/duckdb_dir/features/cityflow_three_clips
  video_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/data/cityflow/data
  video_frames_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/data/cityflow/data
  onames:
    - car
charades:
  dataset_size: 9601
  n_train_selection: 10000
  n_test_selection: 10000
  n_test_distill: 1000
  features_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/duckdb_dir/features/charades_five_clips
  video_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/data/charades/Charades_v1_480
  video_frames_dir: /gscratch/balazinska/enhaoz/VOCAL-UDF/data/charades/frames
  onames:
    - person
    - bag
    - bed
    - blanket
    - book
    - box
    - broom
    - chair
    - closet/cabinet
    - clothes
    - cup/glass/bottle
    - dish
    - door
    - doorknob
    - doorway
    - floor
    - food
    - groceries
    - laptop
    - light
    - medicine
    - mirror
    - paper/notebook
    - phone/camera
    - picture
    - pillow
    - refrigerator
    - sandwich
    - shelf
    - shoe
    - sofa/couch
    - table
    - television
    - towel
    - vacuum
    - window
visprog:
  program_generator:
    temperature: 0.2
    top_p: 0.5